import * as Screens from '@/screens';
const routes = {
  auth: {
    login: 'Login',
    forgot: 'Forgot',
    forgotVerifyOtp: 'ForgotVerifyOtp',
    forgotResetPassword: 'ForgotResetPassword',
    onboarding: 'Onboarding',
    register: 'Register',
    completeProfile: 'CompleteProfile',
  },
  main: {
    settings: 'Settings',
    editProfile: 'EditProfile',
    changePassword: 'ChangePassword',
    privacySettings: 'PrivacySettings',
    privacyFirst: 'PrivacyFirst',
    subscription: 'Subscription',
    manageSubscriptions: 'ManageSubscriptions',
    paymentMethod: 'PaymentMethod',
    help: 'Help',
    support: 'Support',
    cardDetails: 'CardDetails',
    helpAndCenter: 'HelpAndCenter',
    profileDetails: 'ProfileDetails',
    profile: 'Profile',
    notification: 'Notification',
    checkout: 'Checkout',
    mybets: 'Mybets',
    workHistory: 'WorkHistory',
    wageOverview: 'WageOverview',
    myProfile: 'MyProfile',
    setting: 'Setting',
    helpSupport: 'HelpSupport',
    helpHowItWorks: 'HelpHowItWorks',
    routeDetails: 'RouteDetails',
    supportedStores: 'SupportedStores',
    productDetails: 'ProductDetails',
    savingBarcode: 'SavingBarcode',
    savingBarcodeRedeemed: 'SavingBarcodeRedeemed',
},
  tab: {
    home: 'Home',
    deals: 'Deals',
    cashback: 'Cashback',
    insights: 'Insights',
    menu: 'Menu',
    extraWork: 'ExtraWork',
    layover: 'Layover',
    alerts: 'Alerts',
},
  navigator: {
    auth: 'Auth',
    main: 'Main',
    tab: 'Tabs',
  },
} as const;
export const authRoutes = {
  [routes.auth.login]: Screens.Login,
  [routes.auth.forgot]: Screens.Forgot,
  [routes.auth.forgotVerifyOtp]: Screens.ForgotVerifyOtp,
  [routes.auth.forgotResetPassword]: Screens.ForgotResetPassword,
  [routes.auth.onboarding]: Screens.Onboard,
  [routes.auth.register]: Screens.Register,
  [routes.auth.completeProfile]: Screens.CompleteProfile,
};
export const tabRoutes = {
  [routes.tab.home]: Screens.Home,
  [routes.tab.deals]: Screens.Deals,
  [routes.tab.cashback]: Screens.Cashback,
  [routes.tab.insights]: Screens.Insights,
  [routes.tab.menu]: Screens.MenuTab,
  [routes.tab.extraWork]: Screens.ExtraWork,
  [routes.tab.layover]: Screens.Layover,
  [routes.tab.alerts]: Screens.Alerts,
};
export const mainRoutes = {
  [routes.main.settings]: Screens.Settings,
  [routes.main.editProfile]: Screens.EditProfile,
  [routes.main.changePassword]: Screens.ChangePassword,
  [routes.main.privacySettings]: Screens.PrivacySettings,
  [routes.main.privacyFirst]: Screens.PrivacyFirst,
  [routes.main.subscription]: Screens.Subscription,
  [routes.main.manageSubscriptions]: Screens.ManageSubscriptions,
  [routes.main.paymentMethod]: Screens.PaymentMethod,
  [routes.main.help]: Screens.Help,
  [routes.main.support]: Screens.MainSupport,
  [routes.main.cardDetails]: Screens.CardDetails,
  [routes.main.helpAndCenter]: Screens.HelpAndCenter,
  [routes.main.profileDetails]: Screens.ProfileDetails,
  [routes.main.profile]: Screens.Profile,
  [routes.main.notification]: Screens.Notification,
  [routes.main.checkout]: Screens.Checkout,
  [routes.main.mybets]: Screens.Mybets,
  [routes.main.workHistory]: Screens.WorkHistory,
  [routes.main.wageOverview]: Screens.WageOverview,
  [routes.main.myProfile]: Screens.MyProfile,
  [routes.main.setting]: Screens.Setting,
  [routes.main.helpSupport]: Screens.HelpSupport,
  [routes.main.helpHowItWorks]: Screens.HelpHowItWorks,
  [routes.main.routeDetails]: Screens.RouteDetails,
  [routes.main.supportedStores]: Screens.SupportedStores,
  [routes.main.productDetails]: Screens.ProductDetails,
  [routes.main.savingBarcode]: Screens.SavingBarcode,
  [routes.main.savingBarcodeRedeemed]: Screens.SavingBarcodeRedeemed,
};
export default routes;
