/** Route name constants only — no screen imports (avoids require cycles). */
const routes = {
  auth: {
    login: 'Login',
    forgot: 'Forgot',
    forgotVerifyOtp: 'ForgotVerifyOtp',
    forgotResetPassword: 'ForgotResetPassword',
    onboarding: 'Onboarding',
    register: 'Register',
    completeProfile: 'CompleteProfile',
  },
  main: {
    settings: 'Settings',
    editProfile: 'EditProfile',
    changePassword: 'ChangePassword',
    privacySettings: 'PrivacySettings',
    privacyFirst: 'PrivacyFirst',
    subscription: 'Subscription',
    manageSubscriptions: 'ManageSubscriptions',
    paymentMethod: 'PaymentMethod',
    help: 'Help',
    support: 'Support',
    cardDetails: 'CardDetails',
    helpAndCenter: 'HelpAndCenter',
    profileDetails: 'ProfileDetails',
    profile: 'Profile',
    notification: 'Notification',
    checkout: 'Checkout',
    mybets: 'Mybets',
    workHistory: 'WorkHistory',
    wageOverview: 'WageOverview',
    myProfile: 'MyProfile',
    setting: 'Setting',
    helpSupport: 'HelpSupport',
    helpHowItWorks: 'HelpHowItWorks',
    routeDetails: 'RouteDetails',
    supportedStores: 'SupportedStores',
    productDetails: 'ProductDetails',
    savingBarcode: 'SavingBarcode',
    savingBarcodeRedeemed: 'SavingBarcodeRedeemed',
    languageSettings: 'LanguageSettings',
    currencySettings: 'CurrencySettings',
    addIncome: 'AddIncome',
    addExpense: 'AddExpense',
    givingSettings: 'GivingSettings',
    recipientsList: 'RecipientsList',
    addRecipient: 'AddRecipient',
    addDonation: 'AddDonation',
    zakatHub: 'ZakatHub',
  },
  tab: {
    home: 'Home',
    transactions: 'Transactions',
    donate: 'Donate',
    analytics: 'Analytics',
    profileTab: 'ProfileTab',
  },
  navigator: {
    auth: 'Auth',
    main: 'Main',
    tab: 'Tabs',
  },
} as const;

export default routes;
export { routes };
